### Thư viện

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Lấy dữ liệu

In [17]:
def get_data(data_path_sents, data_path_sentiments):
    with open(data_path_sents, 'r', encoding='utf-8') as file:
        sents = file.readlines()
    with open(data_path_sentiments, 'r', encoding='utf-8') as file:
        sentiments = file.readlines()
    return pd.DataFrame({'sentences':sents, 'sentiments':sentiments})

In [21]:
train_data = get_data('train-20241208T060932Z-001/sents.txt', 'train-20241208T060932Z-001/sentiments.txt')
validation_data = get_data('dev-20241208T060957Z-001/sents.txt', 'dev-20241208T060957Z-001/sentiments.txt')
test_data = get_data('test-20241208T060919Z-001/sents.txt', 'test-20241208T060919Z-001/sentiments.txt')

In [22]:
print(train_data.shape)
print(validation_data.shape)
print(test_data.shape)

(11426, 2)
(1583, 2)
(3166, 2)

In [23]:
train_data.head()

                                           sentences sentiments
0                        slide giáo trình đầy đủ .\n        2\n
1   nhiệt tình giảng dạy , gần gũi với sinh viên .\n        2\n
2             đi học đầy đủ full điểm chuyên cần .\n        0\n
3  chưa áp dụng công nghệ thông tin và các thiết ...        0\n
4  thầy giảng bài hay , có nhiều bài tập ví dụ ng...        2\n

In [25]:
validation_data.head()

                                           sentences sentiments
0                         giáo trình chưa cụ thể .\n        0\n
1                                 giảng buồn ngủ .\n        0\n
2                   giáo viên vui tính , tận tâm .\n        2\n
3  giảng viên nên giao bài tập nhiều hơn , chia n...        0\n
4  giảng viên cần giảng bài chi tiết hơn , đi sâu...        0\n

In [24]:
test_data.head()

                                           sentences sentiments
0                         nói tiếng anh lưu loát .\n        2\n
1                         giáo viên rất vui tính .\n        2\n
2                                  cô max có tâm .\n        2\n
3                     giảng bài thu hút , dí dỏm .\n        2\n
4  giáo viên không giảng dạy kiến thức , hướng dẫ...        0\n